### ISSUE TITLE
File permissions

### ISSUE THREAD

**Issue by QCU87Z** [alexellis/phototimer#4]
I am running this python program via SSH and writing the files to an NFS mount.

The files permission mean only the pi can delete them
-rw-r--r-- 1 pi 1001 1758502 May 23 19:05 2017_5_23_19_1495530309537.jpg

How do I get it so the python program writes the files with permissions for everyone. Currently I am just chmod'ing all the files if I need to delete them.

**Comment by alexellis** [comment]
That's an interesting problem. The photos are being written by the `raspistill` CLI - so you could edit the `take.py` file so that it runs `chmod` after taking each frame. Are you running inside or outside of Docker?

**Comment by QCU87Z** [comment]
Outside of docker at the moment. In the future I more than likely will run it in docker but wasn't sure if it was normal behaviour

**Comment by rgee0** [comment]
Its the permissions of the directories, rather than the files, that controls whether the files can be deleted, and by who.  
Where you are relying on `take.py` to create the directory structure putting `os.umask` in the `prepare_dir` function with a suitable argument value could be a simple solution.

**Comment by alexellis** [comment]
Happy for someone to raise a PR - if tested I will consider merging it.

**Comment by alexellis** [comment]
@QCU87Z @rgee0 if I don't hear from either of you I'll close this issue in a few days.
