### ISSUE TITLE
usage questions

### ISSUE THREAD

**Issue by jojo05** [alexellis/phototimer#5]
1) how do I disable the am and pm time boundaries ?
2) I am using a pizero. How do I set time in the laptop so that when I power up a few minutes later the time is roughly ok? 
3) what's metering mode and what options are available?

Thanks

config = {}
config["am"] = 400
config["pm"] = 2000
config["metering_mode"] = "matrix"

**Comment by alexellis** [comment]
1 - The am/pm daylight hours are built into the application - so you'd have to change the code and enable a new configuration flag. Without changing the code you could just make the am/pm hours very close together so that there's barely any gap.

What's your use-case for taking photo stills 24 hours? (just curious)

2 - I'm not sure what you mean. Can you explain?

3 - The metering mode is part of the `raspistill` utility - if you type that in on the command-line it'll print out the help message and the various *Metering mode options*.

**Comment by jojo05** [comment]
1. ok. Use case is view with enough night light, there might not be much movement tough.  
2. I got a pizero and set it up. When I unplug it from the laptop and connect it again I get an april date. Maybe there is a way to set the date when it boots so the date will be more approximate (as there is no network connection in my setup once phototimer is running)
3. Thanks, that was a newbie question. I bought zeroview and set it up inspired by your blog post. Thanks

**Comment by trinitronx** [comment]
@jojo05 :   For a use case taking photos all 24 hours, this is what worked for me:

```
# Hack to ALWAYS take images
config["am"] = -9999
config["pm"] = 9999
```

I created a docker image with these settings in `config.py`.  You can run it like this:

```
docker run -d --restart=always \
           --name=phototimer \
           -v /mnt/data/phototimer/images:/var/image \
           -v /lib/modules:/lib/modules \
           --privileged \
       trinitronx/phototimer:raspberrypi3-armv7hf
```

**Comment by alexellis** [comment]
@trinitronx thanks for answering the question.

I'm closing the issue due to inactivity. It appears that we have a resolution for this.

If someone wants to send a PR for disabling the timer via a configuration item then I would consider merging it. I do not think I have time to do this change myself.
